const CACHE_NAME = 'suji-v1-29-0';
const PRECACHE = [
  "./README.md",
  "./arch.md",
  "./arch_1.1.0.md",
  "./config/game-config.js",
  "./config/storage-keys.js",
  "./config/theme.css",
  "./config/ui-config.js",
  "./css/app-shell.css",
  "./css/base.css",
  "./css/board.css",
  "./css/conflicts.css",
  "./css/dialogs.css",
  "./css/hints.css",
  "./css/level-picker.css",
  "./css/pieces.css",
  "./css/pwa.css",
  "./css/rack.css",
  "./css/responsive.css",
  "./css/tutorial.css",
  "./data/patterns/pattern_01.json",
  "./data/patterns/pattern_02.json",
  "./data/patterns/pattern_03.json",
  "./data/patterns/pattern_04.json",
  "./data/patterns/pattern_05.json",
  "./data/patterns/pattern_06.json",
  "./data/patterns/pattern_07.json",
  "./data/patterns/pattern_08.json",
  "./data/patterns/pattern_09.json",
  "./data/patterns/pattern_10.json",
  "./icons/apple-touch-icon.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon-maskable-512.png",
  "./icons/suji-icon.svg",
  "./index.html",
  "./js/core/app-context.js",
  "./js/core/dom.js",
  "./js/core/events.js",
  "./js/core/state.js",
  "./js/core/utils.js",
  "./js/data/pattern-provider.js",
  "./js/features/drag-drop.js",
  "./js/features/hints.js",
  "./js/features/level-picker.js",
  "./js/features/picture-preview.js",
  "./js/features/settings.js",
  "./js/features/tutorial.js",
  "./js/game/placement-rules.js",
  "./js/game/puzzle-builder.js",
  "./js/game/scoring.js",
  "./js/game/sudoku-generator.js",
  "./js/game/validator.js",
  "./js/layout/rack-layout.js",
  "./js/layout/responsive-layout.js",
  "./js/levels/level-loader.js",
  "./js/levels/level-manager.js",
  "./js/levels/level-registry.js",
  "./js/levels/packs/pack-manager.js",
  "./js/levels/packs/pack-registry.js",
  "./js/levels/progression.js",
  "./js/levels/sponsored/sponsored-pack-provider.js",
  "./js/levels/standard/standard-level-provider.js",
  "./js/levels/standard/standard-progression.js",
  "./js/levels/tutorial/level-001.js",
  "./js/levels/tutorial/level-002.js",
  "./js/levels/tutorial/level-003.js",
  "./js/levels/tutorial/level-004.js",
  "./js/levels/tutorial/level-005.js",
  "./js/levels/types/sponsored-level.js",
  "./js/levels/types/standard-level.js",
  "./js/levels/types/themed-level.js",
  "./js/levels/types/tutorial-level.js",
  "./js/main.js",
  "./js/pwa/install.js",
  "./js/storage/preferences-store.js",
  "./js/storage/progress-store.js",
  "./js/ui/board-view.js",
  "./js/ui/conflict-view.js",
  "./js/ui/dialogs.js",
  "./js/ui/piece-view.js",
  "./js/ui/rack-view.js",
  "./js/ui/stats-view.js",
  "./manifest.webmanifest",
  "./resources/Image_0001.png",
  "./resources/Image_0002.png",
  "./resources/Image_0003.png",
  "./resources/Image_0004.png",
  "./resources/Image_0005.png",
  "./styles.css"
];

self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE_NAME).then(cache => cache.addAll(PRECACHE)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key.startsWith('suji-') && key !== CACHE_NAME).map(key => caches.delete(key)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  const request=event.request; if(request.method!=='GET') return; const url=new URL(request.url); if(url.origin!==self.location.origin) return;
  if(request.mode==='navigate'){
    event.respondWith(fetch(request).then(response=>{ const copy=response.clone(); caches.open(CACHE_NAME).then(cache=>cache.put('./index.html',copy)); return response; }).catch(()=>caches.match('./index.html'))); return;
  }
  event.respondWith(caches.match(request).then(cached=>cached||fetch(request).then(response=>{ if(response&&response.status===200&&response.type==='basic'){ const copy=response.clone(); caches.open(CACHE_NAME).then(cache=>cache.put(request,copy)); } return response; })));
});
